const reportData = {
  test_name: "",
  generate_time: "",
  version: "",
  start_time: "",
  end_time: "",
  test_status: "",
  kpsi: 0,
  risk_number: 0,
  serious_vuln_number: 0,
  high_vuln_number: 0,
  medium_vuln_number: 0,
  low_vuln_number: 0,
  host_number: 0,
  port_number: 0,
  domain_number: 0,
  site_number: 0,
  impact_statistics: {
    cloud_key: 0,
    code_store: 0,
    container: 0,
    controlled_host: 0,
    credential: 0,
    database: 0,
    file: 0,
    sens_info: 0,
  },
  configuration: {
    test_name: "",
    test_target: null,
    exclude_target: null,
    port_type: "",
    module_config: {
      password_burst: null,
      other_burst: null,
      password_validation: null,
      middle_attack: null,
      cause_harm_exploit: null,
      post_penetration: null,
    },
    other_config: {
      company_domains: null,
      git_accounts: null,
      other_accounts: null,
    },
  },
  impact_details: { host: { describe: "", targets: null } },
  vuln_details: {
    serious_vuln: null,
    high_vuln: null,
    medium_vuln: null,
    low_vuln: null,
  },
};
